### ISSUE TITLE
TDWG recommendations

### ISSUE THREAD

**Issue by andrewrodrigues** [gbif/doc-sensitive-species-best-practices#10]
Under https://docs.gbif-uat.org/sensitive-species-best-practices/master/en/#documenting-sensitivity  I would recommend that recommendations to publishers come first before the recommendation to TDWG.  The document should focus on what can practitioners do now and future developments that further facilitate these processes should come later.

**Comment by ArthurChapman** [comment]
@andrewrodrigues I am not sure exactly what you mean here in this section.

**Comment by andrewrodrigues** [comment]
Its a comment on how the the section is currently written, at the end of the section you make clear recommendations 
'Until such time as these standards and protocols are modified, it is recommended that the data be documented in the Comment fields, and as far as possible to record the same type of information that would be included in the recommended fields above, for example, that:
-The data are sensitive
-The primary reasons the data are regarded as sensitive (see Criteria 1–4, Table 1) along with supporting rationale
-The date that the sensitivity of the data should be reviewed
-Precision of the data made available
-Precision of the original data stored or retained`

Would recommend starting with this and then explaining how then talk about how the standard can be improved in the future with additional fields.  This makes it clear for users of the document what they should be doing now, when dealing with sensitive species data.

**Comment by laurarussell** [comment]
Moved recommendations to the Afterword section with edits in pull request #15.
