### ISSUE TITLE
Provide anchor for table 7

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-sensitive-species-best-practices#20]
_Table 7. Method of generalizing geographic coordinates_ currently does not have an id/anchor and can thus not be linked to directly. This in contrast with Table 1 which has an `id` and can be referenced directly: https://docs.gbif.org/sensitive-species-best-practices/master/en/#table-01

```html
<table id="table-01" class="tableblock frame-all grid-all stretch">
```

Can an id be provided for table 7?

**Comment by ArthurChapman** [comment]
@kcopas Can you lease look into this.
