### ISSUE TITLE
Possible issues

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-sensitive-species-best-practices#3]
Making a close read-through to capture a punch list of possible issues or oversights in the draft text and/or its migration to GitHub.

- [x] Propose adjusting initial 'NOTE' to indicate that "Words hyperlinked in the text refer to terms that are included in the Glossary; citations link to sources where they are available online, and to the References/Bibliography where they are not."
- [x] The phrase 'current best practice' in [the introduction](https://docs.gbif-uat.org/sensitive-species-best-practices/master/en/#_scope) is in bold but is not included in the [glossary](https://docs.gbif-uat.org/sensitive-species-best-practices/master/en/#_glossary)

**Comment by ArthurChapman** [comment]
OK Point 1.
unbold point 2.

**Comment by ArthurChapman** [comment]
WIth numbering of Sections. Should **Introduction** be numbered as "1." and others follow on from there?

**Comment by kcopas** [comment]
- [ ] Is there supposed to be a glossary entry for GUIDs? The end of [§4.4](https://docs.gbif-uat.org/sensitive-species-best-practices/master/en/#_duplicates_and_guids) seems to suggest it, but no clear signals elsewhere.

(Apologies if I asked this before—not seeing evidence that I did)

**Comment by kcopas** [comment]
- [ ] Review current Google Doc and sync up any changes in text used to create repo

**Comment by ArthurChapman** [comment]
I have changed many of the GUID references to PIDs (see separate comments to @kcopas).  Not sure they needs adding to Glossary.  If you think they should be added, then the definitions we have in the Georeferencing Best Practice are:

Globally Unique Identifier (GUID) — a 128-bit string of characters applied to one and only one physical or digital entity so that the string uniquely identifies the entity and can be used to refer to the entity. See also Persistent Identifier (PID).

Persistent Identifier (PID) — is a long-lasting reference to a document, file, web page, or other object. The term "persistent identifier" is usually used in the context of digital objects that are accessible over the Internet. There are many options for PIDs, such as Globally Unique Identifiers (GUIDs), Digital Object Identifiers (DOIs), and Universal Unique Identifiers (UUIDs).

**Comment by ArthurChapman** [comment]
I have gone through the document thoroughly, and synced the Google Doc to the master and added comments in a separate document to @kcopas and attached here

The master document looks good and I like what has been done with the Tables.

The way it comes out on PDF still needs some work, especially with Widows and Orphans and adding Section breaks, etc.  I suggest that all Sections in the PDF start on a new page - and especially the Annex, and all Tables (where possible) should be on the one page and not leave an awkward line on one page and the rest on the next page.

A good job so far.

[Comments_AC_20200315_Current Best Practices for Generalizing Sensitive Species Occurrence Data.docx](https://github.com/gbif/doc-sensitive-species-best-practices/files/4333675/Comments_AC_20200315_Current.Best.Practices.for.Generalizing.Sensitive.Species.Occurrence.Data.docx)

**Comment by tucotuco** [comment]
Hmmm, that definition for GUID seems like the definition for a specific type of GUID - a UUID. We need to look at that in Georeferencing Best Practices.

**Comment by ArthurChapman** [comment]
You need to explain the difference @tucotuco. My reading is that generally they are regarded as synonyms.  Som references say that a GUID is Microsofts application of a UUID.

According to IETF [RFC 4122](https://tools.ietf.org/rfc/rfc4122.txt). The Abstract says: "This specification defines a Uniform Resource Name namespace for UUIDs (Universally Unique IDentifier), also known as GUIDs (Globally Unique IDentifier).  A UUID is 128 bits long, and can guarantee uniqueness across space and time.  UUIDs were originally used in the Apollo Network Computing System and later in the Open Software Foundation's (OSF) Distributed Computing Environment (DCE), and then in Microsoft Windows platforms."

Wikipedia  [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) states "A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems. The term globally unique identifier (GUID) is also used, typically in software created by Microsoft."

Tech Terms [GUID](https://techterms.com/definition/guid) defines a GUID as "A GUID is a 128-bit (16 byte) number used by software programs to uniquely identify the location of a data object. "

**Comment by tucotuco** [comment]
In our domain we use GUID as something more general, of which a UUID is one
example. URLs would also be GUIDs, and resolvable. The following sets the
stage very well for how we use the term...

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4400380/

**Comment by ArthurChapman** [comment]
That is one reason that I think Dimitris Koureas suggested we used Persistent IDs (PIDs) rather than GUIDs because he thought we (our domain) were using GUIDs where we really meant PIDs

**Comment by tucotuco** [comment]
The important thing is not to propagate misunderstanding. In Best
Practices, we really mean persistent identifiers that are globally unique,
not necessarily UUIDs.

**Comment by kcopas** [comment]
Thanks, gents. I hope to circle back to this later this week. Two points meanwhile.

1. I have no standing to have a view on PIDs, GUIDs or UUIDs. I raised the issue only because there was one bolded instance of GUID in §4.4 (and not the first one, at that). I will take your direction as to a) which term to use and b) whether it belongs in the glossary.

2. We will do what we can regarding PDF formatting, but, again, to be very clear, it is not the primary version and is one that (at this point) we provide for only for users' convenience. Anything that cannot be resolved with minimal effort and intervention—or that creates issues we have to work around in the HTML version—will not be in scope.

**Comment by ArthurChapman** [comment]
Translations. I just notice that Pensoft uses a suffix to the DOI for Supplementary Material - e.g. https://doi.org/10.3897/biss.4.50889.suppl1. I was thinking that this same method could be used for translated versions of the GBIF publications.  e.g. https://doi.org/10.15468/doc.fm4b-6q42.fr, https://doi.org/10.15468/doc.fm4b-6q42.pt, etc.

**Comment by MattBlissett** [comment]
I've read through to check everything was up-to-date with other changes to the documentation system.  

A minor issue: the link "US Forest Service 2016" was pointing to the Google Docs document for this document. I've changed it to "TODO LINK" so this isn't forgotten, the real link needs to be inserted in section 7 and the bibliography.

Also, the link to EPSG:19986 in section 4 is not defined.

**Comment by kcopas** [comment]
Thanks, @MattBlissett !

**Comment by ArthurChapman** [comment]
Thanks @MattBlissett - the US Forest Service link should be "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/fseprd530660.pdf"

The link for EPSG:19986 in section 4 is "https://epsg.io/19986"
