### ISSUE TITLE
Harmful human activity

### ISSUE THREAD

**Issue by andrewrodrigues** [gbif/doc-sensitive-species-best-practices#5]
Is it worth defining what we mean by harmful human activity? 
Conversion of habitat and targeted collection are both harmful human activities but release of data might might be beneficial for the species´s conservation in the first instance but detrmimental to sthe species´s existence in the second.  IUCN has a a threats classification system that is used for identifying the threat (human and non-human) that a species might be subject to https://www.iucnredlist.org/resources/threat-classification-scheme

**Comment by ArthurChapman** [comment]
@kcopas 

Under __§Glossary__

Add

__harmful human activiy__
human activities or processes that, in an adverse way, have impacted, are impacting, or may impact the status of the taxon being assessed (e.g., unsustainable fishing or logging, hunting, harvesting, agriculture, housing developments, etc.) (see IUCN 2020).

Under __§References__

Add

IUCN (2020) Threats Classification Scheme (Version 3.2). https://www.iucnredlist.org/resources/threat-classification-scheme.
