### ISSUE TITLE
Access Constraints

### ISSUE THREAD

**Issue by andrewrodrigues** [gbif/doc-sensitive-species-best-practices#7]
In https://docs.gbif-uat.org/sensitive-species-best-practices/master/en/#documenting-sensitivity there is talk of an access contstraints field in metadata.  However I cannot find it in the GBIF metadata profile https://github.com/gbif/ipt/wiki/GMPHowToGuide.  I would say that generally in the documentation section it is unclear what is recommended for metadata and what is recommended for "record-level metadata".  This could be clearer.

**Comment by ArthurChapman** [comment]
As far as I know, this is not yet available - perhaps someone from GBIF can comment.  I will look at ypour second point - thanks

**Comment by ArthurChapman** [comment]
@andrewrodrigues wrt "record level metadata" I though this was fairly obvious from the first two sentences - i.e. as opposed to dataset metadata (metadata on the dataset as a whole).   Also what is recommended for metadata at the record level is documented in Table 8.

**Comment by andrewrodrigues** [comment]
@ArthurChapman my understanding reading the section is that table 8 is a set of recommendations for an extension to Darwin core based and so was something that would ideally be implemented in the future.  Just wasn´t clear to me what  would be recommended now given current limitations.

**Comment by laurarussell** [comment]
Addressed now in Section 5 and 5.1 with Pull Request #16 by removing emphasis to 'Access Constraints". Instead reads as access constraints. Reworked last sentence at end of section 5.1.
