### ISSUE TITLE
Spatial Fit 

### ISSUE THREAD

**Issue by andrewrodrigues** [gbif/doc-sensitive-species-best-practices#8]
https://github.com/gbif/ipt/wiki/GMPHowToGuide.  Is this being recommended as an additional value that data publishers could add to generalized records to give a better idea of to what extent the record has been geenralized?  Unsure what the recommendation is in this section.

**Comment by ArthurChapman** [comment]
This is something for GBIF, however, Spatial Fit is discussed in detail in the forthcoming book on Georeferencing Best Practices which should be available for Public Review within the next month or so.

@kcopas 

In __5.2__  I think we should add the reference to the new Georeferenceing Best Practices in Line 1 - although it is referenced in line 4.

Change "(Chapman and Wieczorek 2006)" to "(Chapman and Wieczorek 2006, 2020)"  with the additional link to "https://doi.org/10.15468/doc-gg7h-s853"

The reference is already in the References
